// src/constants/roles.js
export const ROLES = {
    WAREHOUSE_ADMIN: 'WAREHOUSE_ADMIN',
    SYSTEM_ADMIN: 'SYSTEM_ADMIN',
    AFTERSALES_STAFF: 'AFTERSALES_STAFF'
  }
  
  export const ROLE_LABELS = {
    [ROLES.WAREHOUSE_ADMIN]: '仓库管理员',
    [ROLES.SYSTEM_ADMIN]: '系统管理员',
    [ROLES.AFTERSALES_STAFF]: '售后人员'
  }
  
  // 页面权限配置
  export const PAGE_PERMISSIONS = {
    PRODUCTS: [ROLES.WAREHOUSE_ADMIN, ROLES.SYSTEM_ADMIN],
    INBOUNDS: [ROLES.WAREHOUSE_ADMIN, ROLES.SYSTEM_ADMIN],
    OUTBOUNDS: [ROLES.WAREHOUSE_ADMIN, ROLES.SYSTEM_ADMIN],
    RETURNS: [ROLES.WAREHOUSE_ADMIN, ROLES.AFTERSALES_STAFF, ROLES.SYSTEM_ADMIN]
  }
  
  export default {
    ROLES,
    ROLE_LABELS,
    PAGE_PERMISSIONS
  }